### ISSUE TITLE
Links not given

### ISSUE THREAD

**Issue by Rakesh95** [YUPlayGod/factory-image-flash-tools#1]
In Steps to flash factory image the pakage download links are not given.
![capture](https://cloud.githubusercontent.com/assets/10557582/5772212/15f390c8-9d74-11e4-8a84-30f764747921.JPG)

**Comment by RohanAJoshi** [comment]
me too, waiting for links..

**Comment by DooMLoRD** [comment]
We will be releasing factory images soon.

**Comment by ayushmathur** [comment]
what about the drivers @DooMLoRD i read your thread on yu forums. waiting for that to unlock boot loader

**Comment by DooMLoRD** [comment]
We are working on it

**Comment by ayushmathur** [comment]
well, in the mean time i installed the universal driver using pda.net. there is no problem with that right? @DooMLoRD

**Comment by Rakesh95** [comment]
please, When are links going to come
